package com.wifisentinel.core.detectors

object FindingTextKeys {
    const val WEAK_SECURITY_TITLE = "finding_weak_security_title"
    const val WEAK_SECURITY_BODY = "finding_weak_security_body"
    const val UNKNOWN_SECURITY_TITLE = "finding_unknown_security_title"
    const val UNKNOWN_SECURITY_BODY = "finding_unknown_security_body"
    const val DNS_SUSPICIOUS_TITLE = "finding_dns_suspicious_title"
    const val DNS_SUSPICIOUS_BODY = "finding_dns_suspicious_body"
    const val CAPTIVE_PORTAL_TITLE = "finding_captive_portal_title"
    const val CAPTIVE_PORTAL_BODY = "finding_captive_portal_body"
    const val CAPTIVE_PORTAL_SUSPICIOUS_TITLE = "finding_captive_portal_suspicious_title"
    const val CAPTIVE_PORTAL_SUSPICIOUS_BODY = "finding_captive_portal_suspicious_body"
    const val DISCONNECT_ANOMALY_TITLE = "finding_disconnect_anomaly_title"
    const val DISCONNECT_ANOMALY_BODY = "finding_disconnect_anomaly_body"
    const val GATEWAY_ANOMALY_TITLE = "finding_gateway_anomaly_title"
    const val GATEWAY_ANOMALY_BODY = "finding_gateway_anomaly_body"
    const val PINNED_DNS_TITLE = "finding_pinned_dns_title"
    const val PINNED_DNS_BODY = "finding_pinned_dns_body"
    const val EVIL_TWIN_BSSID_TITLE = "finding_evil_twin_bssid_title"
    const val EVIL_TWIN_BSSID_BODY = "finding_evil_twin_bssid_body"
    const val EVIL_TWIN_SECURITY_TITLE = "finding_evil_twin_security_title"
    const val EVIL_TWIN_SECURITY_BODY = "finding_evil_twin_security_body"
    const val EVIL_TWIN_BAND_TITLE = "finding_evil_twin_band_title"
    const val EVIL_TWIN_BAND_BODY = "finding_evil_twin_band_body"
    const val TRUSTED_LIKE_TITLE = "finding_trusted_like_title"
    const val TRUSTED_LIKE_BODY = "finding_trusted_like_body"
    const val SIMILAR_NETWORKS_TITLE = "finding_similar_networks_title"
    const val SIMILAR_NETWORKS_BODY = "finding_similar_networks_body"
    const val MESH_TOO_MANY_BSSID_TITLE = "finding_mesh_too_many_bssid_title"
    const val MESH_TOO_MANY_BSSID_BODY = "finding_mesh_too_many_bssid_body"
    const val UNUSUAL_BEHAVIOR_TITLE = "finding_unusual_behavior_title"
    const val UNUSUAL_BEHAVIOR_BODY = "finding_unusual_behavior_body"
    const val LOOKALIKE_SSID_TITLE = "finding_lookalike_ssid_title"
    const val LOOKALIKE_SSID_BODY = "finding_lookalike_ssid_body"
}
