package com.wifisentinel.core.detectors

object EvidenceKeys {
    const val SECURITY_TYPE = "security_type"
    const val SYSTEM_DNS = "system_dns"
    const val EMPTY_SYSTEM_DOMAINS = "empty_system_domains"
    const val PRIVATE_ONLY_DOMAINS = "private_only_domains"
    const val MISMATCH_DOMAINS = "mismatch_domains"
    const val CAPTIVE_PORTAL = "captive_portal"
    const val PORTAL_REDIRECTS = "portal_redirects"
    const val PORTAL_HTTP = "portal_http"
    const val PORTAL_PUNYCODE = "portal_punycode"
    const val CURRENT_BSSID = "current_bssid"
    const val OBSERVED_BSSIDS = "observed_bssids"
    const val ALLOWED_BSSIDS = "allowed_bssids"
    const val EXPECTED_SECURITY = "expected_security"
    const val CURRENT_SECURITY = "current_security"
    const val EXPECTED_BAND = "expected_band"
    const val CURRENT_BAND = "current_band"
    const val SIMILAR_TRUSTED = "similar_trusted"
    const val SIMILAR_SSIDS = "similar_ssids"
    const val SEEN_SSID = "seen_ssid"
    const val BASE_SSID = "base_ssid"
    const val TRUSTED_SSID = "trusted_ssid"
    const val EXPECTED_DNS = "expected_dns"
    const val CURRENT_DNS = "current_dns"
    const val RECONNECTS = "reconnects"
    const val GATEWAY_IPS = "gateway_ips"
    const val NEW_BSSID_COUNT = "new_bssid_count"
    const val MAX_NEW_BSSID = "max_new_bssid"
    const val BASELINE_BSSID_COUNT = "baseline_bssid_count"
    const val CURRENT_BSSID_COUNT = "current_bssid_count"
    const val BASELINE_DNS_CHANGES = "baseline_dns_changes"
    const val CURRENT_BAND_SIMPLE = "current_band_simple"
    const val BASELINE_MAIN_BAND = "baseline_main_band"
    const val LOOKALIKE_TARGET = "lookalike_target"
    const val LOOKALIKE_FOUND = "lookalike_found"
    const val LOOKALIKE_DIFF = "lookalike_diff"
}
